In [1]:
import requests
import json
import sys
import os
from dotenv import load_dotenv
load_dotenv()
import pandas as pd

In [2]:
def requestyelp(business):
    yelp_api_key = os.getenv("YELP_API_KEY")
    if not yelp_api_key:
        raise ValueError("No key provided")
    else:
        print("The key provided is: ", yelp_api_key[0:5])

    url='https://api.yelp.com/v3/businesses/search'
    headers = {'Authorization': 'Bearer %s' % yelp_api_key}

    info = []
    for offset in range(0, 1000, 50):
        params = {'limit': 50,'term':business,'location':'new york','offset': offset, 'radius':5000}
        req=requests.get(url, params=params, headers=headers)

        if req.status_code == 200:
                info += req.json()['businesses']
        elif req.status_code == 400:
                print('400 Bad Request')
                break
                      
    print('The status code is {}'.format(req.status_code))
    
    return info

In [3]:
#json.loads(req.text)

starbucks = requestyelp("starbucks")
starbucks[0]

The key provided is:  zPUE-
The status code is 200

{'id': 'xAvwjM0F5LN9g3yFsk9e0w',
 'alias': 'starbucks-brooklyn-78',
 'name': 'Starbucks',
 'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/aTZv043RR8uGZX8U2k6rpg/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/starbucks-brooklyn-78?adjust_creative=Pv4KgwVPErnaJnrLXRjn5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=Pv4KgwVPErnaJnrLXRjn5g',
 'review_count': 9,
 'categories': [{'alias': 'coffee', 'title': 'Coffee & Tea'}],
 'rating': 4.0,
 'coordinates': {'latitude': 40.702818, 'longitude': -73.993666},
 'transactions': [],
 'price': '$$',
 'location': {'address1': '11 Old Fulton St.',
  'address2': '',
  'address3': None,
  'city': 'Brooklyn',
  'zip_code': '11201',
  'country': 'US',
  'state': 'NY',
  'display_address': ['11 Old Fulton St.', 'Brooklyn, NY 11201']},
 'phone': '+19176857717',
 'display_phone': '(917) 685-7717',
 'distance': 296.84014710793184}

In [4]:
print(len(starbucks))

1000

In [5]:
def tabla(company):
    info = []
    for i in company:
        venues={ 
            'name': i['name'],
            'categories': i['alias'],
            'city': i['location']['city'],
            'geolocation': {'type': 'Point', 'coordinates':[i['coordinates']['longitude'],i['coordinates']['latitude']]}                    }
        info.append(venues)
    company_info = pd.DataFrame(info)
    return company_info

In [6]:
starbucks_df = tabla(starbucks)
starbucks_df.head(50)

,name,categories,city,geolocation
0,Starbucks,starbucks-brooklyn-78,Brooklyn,"{'type': 'Point', 'coordinates': [-73.993666, ..."
1,Starbucks,starbucks-brooklyn-21,Brooklyn,"{'type': 'Point', 'coordinates': [-73.99080629..."
2,Starbucks,starbucks-new-york-524,New York,"{'type': 'Point', 'coordinates': [-74.000916, ..."
3,Starbucks,starbucks-new-york-217,New York,"{'type': 'Point', 'coordinates': [-74.004971, ..."
4,Starbucks,starbucks-new-york-567,New York,"{'type': 'Point', 'coordinates': [-74.006685, ..."
5,Starbucks,starbucks-new-york-290,New York,"{'type': 'Point', 'coordinates': [-74.007159, ..."
6,Starbucks,starbucks-new-york-381,New York,"{'type': 'Point', 'coordinates': [-74.007387, ..."
7,Starbucks,starbucks-brooklyn-17,Brooklyn,"{'type': 'Point', 'coordinates': [-73.993978, ..."
8,Starbucks,starbucks-new-york-346,New York,"{'type': 'Point', 'coordinates': [-74.008696, ..."
9,Starbucks,starbucks-new-york-506,New York,"{'type': 'Point', 'coordinates': [-74.009001, ..."
10,Starbucks,starbucks-new-york-395,New York,"{'type': 'Point', 'coordinates': [-74.00673000..."
11,Starbucks,starbucks-new-york-214,New York,"{'type': 'Point', 'coordinates': [-74.00799, 4..."
12,Starbucks,starbucks-new-york-404,New York,"{'type': 'Point', 'coordinates': [-74.009313, ..."
13,Starbucks,starbucks-new-york-477,New York,"{'type': 'Point', 'coordinates': [-74.008533, ..."
14,Starbucks,starbucks-new-york-229,New York,"{'type': 'Point', 'coordinates': [-74.003125, ..."
15,Starbucks,starbucks-new-york-264,New York,"{'type': 'Point', 'coordinates': [-74.008202, ..."
16,Starbucks,starbucks-brooklyn-6,Brooklyn,"{'type': 'Point', 'coordinates': [-73.9867893,..."
17,Starbucks,starbucks-new-york-436,New York,"{'type': 'Point', 'coordinates': [-74.010976, ..."
18,Starbucks,starbucks-new-york-143,New York,"{'type': 'Point', 'coordinates': [-74.01133, 4..."
19,Starbucks,starbucks-new-york-131,New York,"{'type': 'Point', 'coordinates': [-74.005956, ..."
20,Starbucks,starbucks-new-york-295,New York,"{'type': 'Point', 'coordinates': [-74.011055, ..."
21,Starbucks,starbucks-brooklyn-14,Brooklyn,"{'type': 'Point', 'coordinates': [-73.991201, ..."
22,Starbucks,starbucks-new-york-345,New York,"{'type': 'Point', 'coordinates': [-74.010363, ..."
23,Starbucks,starbucks-new-york-278,New York,"{'type': 'Point', 'coordinates': [-73.999961, ..."
24,Starbucks,starbucks-brooklyn-40,Brooklyn,"{'type': 'Point', 'coordinates': [-73.982911, ..."
25,Starbucks,starbucks-new-york-434,New York,"{'type': 'Point', 'coordinates': [-74.012051, ..."
26,Starbucks,starbucks-new-york-128,New York,"{'type': 'Point', 'coordinates': [-74.009077, ..."
27,Starbucks,starbucks-new-york-574,New York,"{'type': 'Point', 'coordinates': [-74.011793, ..."
28,Starbucks,starbucks-new-york-511,New York,"{'type': 'Point', 'coordinates': [-74.01087, 4..."
29,Starbucks,starbucks-new-york-560,New York,"{'type': 'Point', 'coordinates': [-74.012733, ..."
30,Starbucks,starbucks-brooklyn-32,Brooklyn,"{'type': 'Point', 'coordinates': [-73.988548, ..."
31,Starbucks,starbucks-new-york-189,New York,"{'type': 'Point', 'coordinates': [-74.0130866,..."
32,Starbucks,starbucks-new-york-428,New York,"{'type': 'Point', 'coordinates': [-73.989977, ..."
33,Starbucks,starbucks-new-york-575,New York,"{'type': 'Point', 'coordinates': [-74.013011, ..."
34,Starbucks,starbucks-new-york-215,New York,"{'type': 'Point', 'coordinates': [-74.002524, ..."
35,Starbucks,starbucks-new-york-537,New York,"{'type': 'Point', 'coordinates': [-73.99913, 4..."
36,Starbucks,starbucks-new-york-380,New York,"{'type': 'Point', 'coordinates': [-74.009003, ..."
37,Starbucks,starbucks-new-york-111,New York,"{'type': 'Point', 'coordinates': [-74.014093, ..."
38,Starbucks,starbucks-new-york-510,New York,"{'type': 'Point', 'coordinates': [-74.014155, ..."
39,Starbucks,starbucks-brooklyn-69,Brooklyn,"{'type': 'Point', 'coordinates': [-73.984355, ..."
40,Starbucks,starbucks-brooklyn-76,Brooklyn,"{'type': 'Point', 'coordinates': [-73.98632603..."
41,Starbucks,starbucks-new-york-294,New York,"{'type': 'Point', 'coordinates': [-74.007305, ..."
42,Starbucks,starbucks-new-york-387,New York,"{'type': 'Point', 'coordinates': [-74.004979, ..."
43,Starbucks,starbucks-brooklyn-73,Brooklyn,"{'type': 'Point', 'coordinates': [-73.98254, 4..."
44,Starbucks,starbucks-brooklyn-16,Brooklyn,"{'type': 'Point', 'coordinates': [-73.992748, ..."
45,Starbucks,starbucks-new-york-417,New York,"{'type': 'Point', 'coordinates': [-74.015373, ..."
46,Starbucks,starbucks-new-york-553,New York,"{'type': 'Point', 'coordinates': [-73.997942, ..."
47,Starbucks,starbucks-brooklyn-77,Brooklyn,"{'type': 'Point', 'coordinates': [-73.98563, 4..."
48,Starbucks Reserve,starbucks-reserve-new-york-4,New York,"{'type': 'Point', 'coordinates': [-74.015465, ..."
49,Starbucks,starbucks-brooklyn-50,Brooklyn,"{'type': 'Point', 'coordinates': [-73.980887, ..."

In [7]:
starbucks_df = starbucks_df[['Starbucks' in x for x in starbucks_df['name']]]
starbucks_df

,name,categories,city,geolocation
0,Starbucks,starbucks-brooklyn-78,Brooklyn,"{'type': 'Point', 'coordinates': [-73.993666, ..."
1,Starbucks,starbucks-brooklyn-21,Brooklyn,"{'type': 'Point', 'coordinates': [-73.99080629..."
2,Starbucks,starbucks-new-york-524,New York,"{'type': 'Point', 'coordinates': [-74.000916, ..."
3,Starbucks,starbucks-new-york-217,New York,"{'type': 'Point', 'coordinates': [-74.004971, ..."
4,Starbucks,starbucks-new-york-567,New York,"{'type': 'Point', 'coordinates': [-74.006685, ..."
...,...,...,...,...
254,Starbucks,starbucks-new-york-499,New York,"{'type': 'Point', 'coordinates': [-73.979878, ..."
255,Starbucks,starbucks-sunnyside,Sunnyside,"{'type': 'Point', 'coordinates': [-73.9182384,..."
256,Starbucks,starbucks-new-york-480,New York,"{'type': 'Point', 'coordinates': [-73.984146, ..."
257,Starbucks,starbucks-new-york-351,New York,"{'type': 'Point', 'coordinates': [-73.954675, ..."
258,Starbucks,starbucks-new-york-354,New York,"{'type': 'Point', 'coordinates': [-73.956935, ..."

In [16]:
starbucks_df.to_json('./starbucks1_api.json', orient='records')

In [10]:
restaurants = requestyelp("vegan")
restaurants[0]

The key provided is:  zPUE-
The status code is 200

{'id': 'XipQLDbyTl5tsLlyzAWzug',
 'alias': 'jajaja-new-york',
 'name': 'Jajaja',
 'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/6HT76TsvGr6XtRVzBi4S_g/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/jajaja-new-york?adjust_creative=Pv4KgwVPErnaJnrLXRjn5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=Pv4KgwVPErnaJnrLXRjn5g',
 'review_count': 852,
 'categories': [{'alias': 'mexican', 'title': 'Mexican'},
  {'alias': 'vegan', 'title': 'Vegan'},
  {'alias': 'bars', 'title': 'Bars'}],
 'rating': 4.5,
 'coordinates': {'latitude': 40.7141530317142, 'longitude': -73.9904247969389},
 'transactions': ['pickup', 'restaurant_reservation', 'delivery'],
 'price': '$$',
 'location': {'address1': '162 E Broadway',
  'address2': '',
  'address3': None,
  'city': 'New York',
  'zip_code': '10002',
  'country': 'US',
  'state': 'NY',
  'display_address': ['162 E Broadway', 'New York, NY 10002']},
 'phone': '+16468835453',
 'display_phone': '(646) 883-5453',
 'distance': 1021.7274074140097}

In [13]:
restaurant_df = tabla(restaurants)
restaurant_df.head(50)

,name,categories,city,geolocation
0,Jajaja,jajaja-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99042479..."
1,Petisco Vegano,petisco-vegano-new-york,New York,"{'type': 'Point', 'coordinates': [-73.988805, ..."
2,Spicy Moon,spicy-moon-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98722, 4..."
3,XYST,xyst-new-york-2,New York,"{'type': 'Point', 'coordinates': [-73.99444, 4..."
4,Jajaja,jajaja-new-york-4,New York,"{'type': 'Point', 'coordinates': [-74.00455, 4..."
5,by CHLOE,by-chloe-new-york-32,New York,"{'type': 'Point', 'coordinates': [-74.001021, ..."
6,Urban Vegan Kitchen,urban-vegan-kitchen-new-york,New York,"{'type': 'Point', 'coordinates': [-74.00368, 4..."
7,Divya's Kitchen,divyas-kitchen-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98849, 4..."
8,Blossom,blossom-new-york-3,New York,"{'type': 'Point', 'coordinates': [-74.002365, ..."
9,Ladybird,ladybird-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98477127..."
10,Happy Zoe Vegan Bakery,happy-zoe-vegan-bakery-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.949646, ..."
11,Dirt Candy,dirt-candy-new-york-2,New York,"{'type': 'Point', 'coordinates': [-73.9907183,..."
12,Greedi Vegan,greedi-vegan-brooklyn-7,Brooklyn,"{'type': 'Point', 'coordinates': [-73.9523247,..."
13,Patty Wagon Express,patty-wagon-express-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.9693814,..."
14,Rip’s Malt Shop,rip-s-malt-shop-new-york,New York,"{'type': 'Point', 'coordinates': [-74.000412, ..."
15,Le Botaniste,le-botaniste-new-york-4,New York,"{'type': 'Point', 'coordinates': [-74.0002028,..."
16,Avant Garden,avant-garden-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98402, 4..."
17,GLUR Thai,glur-thai-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99665, 4..."
18,Red Bamboo,red-bamboo-new-york,New York,"{'type': 'Point', 'coordinates': [-74.00035464..."
19,Honeybee’s,honeybee-s-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98403, 4..."
20,Vegan Love,vegan-love-new-york-2,New York,"{'type': 'Point', 'coordinates': [-73.98325360..."
21,Franchia Vegan Cafe,franchia-vegan-cafe-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98124234..."
22,Rip's Malt Shop,rips-malt-shop-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.9719, 40..."
23,Peacefood Cafe Downtown,peacefood-cafe-downtown-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99297513..."
24,Jungle Cafe,jungle-cafe-brooklyn-2,Brooklyn,"{'type': 'Point', 'coordinates': [-73.954885, ..."
25,Orchard Grocer,orchard-grocer-new-york,New York,"{'type': 'Point', 'coordinates': [-73.990187, ..."
26,Original Buddha Bodai Kosher Vegetarian Restau...,original-buddha-bodai-kosher-vegetarian-restau...,New York,"{'type': 'Point', 'coordinates': [-73.9989484,..."
27,Bar Verde,bar-verde-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98973613..."
28,Copper Branch,copper-branch-new-york-2,New York,"{'type': 'Point', 'coordinates': [-74.00134, 4..."
29,Sacred Chow,sacred-chow-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99944, 4..."
30,Double Zero,double-zero-new-york,New York,"{'type': 'Point', 'coordinates': [-73.9896645,..."
31,Bar Velo Brooklyn,bar-velo-brooklyn-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.954429, ..."
32,Nix,nix-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99359, 4..."
33,American Vegan,american-vegan-brooklyn-2,Brooklyn,"{'type': 'Point', 'coordinates': [-73.96896, 4..."
34,The Cinnamon Snail,the-cinnamon-snail-new-york-7,New York,"{'type': 'Point', 'coordinates': [-73.99196867..."
35,Bali Kitchen,bali-kitchen-new-york-2,New York,"{'type': 'Point', 'coordinates': [-73.987617, ..."
36,Govinda's Vegetarian,govindas-vegetarian-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.98241, 4..."
37,Artistic Pizza,artistic-pizza-new-york,New York,"{'type': 'Point', 'coordinates': [-74.00044, 4..."
38,Superiority Burger,superiority-burger-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98355, 4..."
39,by CHLOE,by-chloe-new-york-31,New York,"{'type': 'Point', 'coordinates': [-73.99292, 4..."
40,Delice & Sarrasin,delice-and-sarrasin-new-york,New York,"{'type': 'Point', 'coordinates': [-74.00065, 4..."
41,Marty's V Burger,martys-v-burger-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98257100..."
42,VSPOT,vspot-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.9795, 40..."
43,Noodlelove,noodlelove-new-york-2,New York,"{'type': 'Point', 'coordinates': [-73.9956235,..."
44,V 4 Vegan,v-4-vegan-new-york-5,New York,"{'type': 'Point', 'coordinates': [-73.98727, 4..."
45,Black Flamingo,black-flamingo-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.953916, ..."
46,Vegan Food Court,vegan-food-court-new-york,New York,"{'type': 'Point', 'coordinates': [-73.989209, ..."
47,Ital Kitchen,ital-kitchen-brooklyn-2,Brooklyn,"{'type': 'Point', 'coordinates': [-73.95804, 4..."
48,Riverdel,riverdel-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.96307, 4..."
49,Yeah Dawg Vegan,yeah-dawg-vegan-brooklyn,Brooklyn,"{'type': 'Point', 'coordinates': [-73.94766235..."

In [14]:
restaurant_df = restaurant_df[['New York' in x for x in restaurant_df['city']]]
restaurant_df

,name,categories,city,geolocation
0,Jajaja,jajaja-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99042479..."
1,Petisco Vegano,petisco-vegano-new-york,New York,"{'type': 'Point', 'coordinates': [-73.988805, ..."
2,Spicy Moon,spicy-moon-new-york,New York,"{'type': 'Point', 'coordinates': [-73.98722, 4..."
3,XYST,xyst-new-york-2,New York,"{'type': 'Point', 'coordinates': [-73.99444, 4..."
4,Jajaja,jajaja-new-york-4,New York,"{'type': 'Point', 'coordinates': [-74.00455, 4..."
...,...,...,...,...
993,Shuka,shuka-new-york-3,New York,"{'type': 'Point', 'coordinates': [-74.00283, 4..."
995,Bareburger,bareburger-new-york-4,New York,"{'type': 'Point', 'coordinates': [-73.97814, 4..."
996,Cheong Fun Cart,cheong-fun-cart-new-york,New York,"{'type': 'Point', 'coordinates': [-73.99637368..."
997,Del Posto,del-posto-new-york,New York,"{'type': 'Point', 'coordinates': [-74.00753301..."
999,DOMODOMO New York,domodomo-new-york-new-york-2,New York,"{'type': 'Point', 'coordinates': [-74.00167, 4..."

In [17]:
restaurant_df.to_json('./vegan1_api.json', orient='records')