In [306]:
from pymongo import MongoClient
import pandas as pd
import re
import folium

In [307]:
def connectCollection(database, collection):
    client = MongoClient()
    db = client[database]
    coll = db[collection]
    return db, coll

In [308]:
db, coll = connectCollection('companies','companies')
print(coll.json)

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'companies'), 'companies.json')

In [309]:
extraer = [
    { "$unwind": "$offices"},
    {"$match": {"$and":
            [{"founded_year": {"$gte": 2009}},
             {"deadpooled_year": None},
             {"total_money_raised": {"$exists": True, "$ne": "$0"}},
             {"offices.latitude": {"$exists": True, "$ne": None}},
             {"offices.longitude": {"$exists": True, "$ne": None}}]}}]

oficinas_fuera = list(coll.aggregate(extraer))


print(oficinas_fuera[0])

{'_id': ObjectId('52cdef7c4bab8bd675297f94'), 'name': 'PeekYou', 'permalink': 'peekyou', 'crunchbase_url': 'http://www.crunchbase.com/company/peekyou', 'homepage_url': 'http://www.peekyou.com', 'blog_url': 'http://www.peekyou.biz', 'blog_feed_url': 'http://blog.peekyou.com/feed/', 'twitter_username': 'peekyou', 'category_code': 'search', 'number_of_employees': 20, 'founded_year': 2012, 'founded_month': 11, 'founded_day': 2, 'deadpooled_year': None, 'deadpooled_month': None, 'deadpooled_day': None, 'deadpooled_url': None, 'tag_list': 'social-crm, database, peekyou, peoplesearch, engine, people, search, directory, social, google', 'alias_list': None, 'email_address': 'info@peekyou.com', 'phone_number': '', 'description': '', 'created_at': 'Fri Aug 31 12:46:53 UTC 2007', 'updated_at': 'Wed Jul 10 10:13:16 UTC 2013', 'overview': '<p>PeekYou places the individual at the center of the Internet. For every public weblink, PeekYou tries to answer the question, &#8220;Who made it?&#8221; or, where applicable, &#8220;Whom is it about?&#8221; So far, we&#8217;ve answered those questions for a billion links and counting. Our patented technology analyzes content from over sixty social sites, news sources, homepages and blog platforms and identifies the actual people behind it, combining their scattered digital footprints into a comprehensive record of their online identity.</p>\n\n<p>Google calculates the likelihood of any link being associated to a keyword. PeekYou calculates the likelihood of any link being associated to an individual.</p>\n\n<p>The company was founded in 2006 by Michael Hussey and is headquartered in New York City.</p>', 'image': {'available_sizes': [[[150, 36], 'assets/images/resized/0011/9733/119733v6-max-150x150.png'], [[250, 61], 'assets/images/resized/0011/9733/119733v6-max-250x250.png'], [[413, 101], 'assets/images/resized/0011/9733/119733v6-max-450x450.png']], 'attribution': None}, 'products': [{'name': 'PeekYou.com', 'permalink': 'peekyou'}, {'name': 'PeekAnalytics', 'permalink': 'peekanalytics'}, {'name': 'PeekAPI', 'permalink': 'peekapi'}], 'relationships': [{'is_past': False, 'title': 'Chairman of the Board', 'person': {'first_name': 'Kimberley', 'last_name': 'Partoll', 'permalink': 'kimberley-partoll'}}, {'is_past': False, 'title': 'CEO/Founder', 'person': {'first_name': 'Michael', 'last_name': 'Hussey', 'permalink': 'michael-hussey'}}, {'is_past': False, 'title': 'CTO', 'person': {'first_name': 'Venky', 'last_name': 'Someswaran', 'permalink': 'venky-someswaran'}}, {'is_past': False, 'title': 'CIO', 'person': {'first_name': 'Pavel', 'last_name': 'Baranov', 'permalink': 'pavel-baranov'}}, {'is_past': False, 'title': 'VP of Operations', 'person': {'first_name': 'Chris', 'last_name': 'Klipple', 'permalink': 'chris-klipple'}}, {'is_past': False, 'title': 'Lead Developer', 'person': {'first_name': 'Eray', 'last_name': 'Cetiner', 'permalink': 'eray-cetiner'}}, {'is_past': False, 'title': 'Director', 'person': {'first_name': 'Baldev', 'last_name': 'Duggal', 'permalink': 'baldev-duggal'}}, {'is_past': False, 'title': 'President', 'person': {'first_name': 'Tom', 'last_name': 'Lynch', 'permalink': 'tom-lynch'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Andy', 'last_name': 'Tuck', 'permalink': 'andy-tuck'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Marshall', 'last_name': 'Sponder', 'permalink': 'marshall-sponder'}}, {'is_past': False, 'title': 'Lead Developer', 'person': {'first_name': 'Dasara', 'last_name': 'Kushi', 'permalink': 'dasara-kushi'}}, {'is_past': False, 'title': 'Art Director', 'person': {'first_name': 'Lane', 'last_name': 'Gillespie', 'permalink': 'lane-gillespie'}}, {'is_past': False, 'title': 'Investment Banker', 'person': {'first_name': 'Phil', 'last_name': 'Fresen', 'permalink': 'phil-fresen'}}, {'is_past': False, 'title': 'Developer', 'person': {'first_name': 'Oleg', 'last_name': 'Borkov', 'permalink': 'oleg-borkov'}}, {'is_past': False, 'title': 'Board of Directors', 'person': {'first_name': 'Peter', 'last_name': 'Bordes', 'permalink': 'peter-bordes'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Francine', 'last_name': 'Hardaway', 'permalink': 'francine-hardaway'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Sebastian', 'last_name': 'Haigh', 'permalink': 'sebastian-haigh'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Stephen', 'last_name': 'Shearin', 'permalink': 'stephen-shearin'}}, {'is_past': False, 'title': 'Software Engineer', 'person': {'first_name': 'Amauris', 'last_name': 'De Jesus', 'permalink': 'amauris-de-jesus'}}, {'is_past': False, 'title': 'Software Engineer', 'person': {'first_name': 'Mikhail', 'last_name': 'Dovgilev', 'permalink': 'mikhail-dovgilev'}}, {'is_past': False, 'title': 'Developer', 'person': {'first_name': 'Ronn', 'last_name': 'Tan', 'permalink': 'ronn-tan'}}, {'is_past': True, 'title': 'CFO', 'person': {'first_name': 'Tom', 'last_name': 'Lynch', 'permalink': 'tom-lynch'}}, {'is_past': True, 'title': 'President/COO', 'person': {'first_name': 'Eric', 'last_name': 'Ludwig', 'permalink': 'eric-ludwig-3'}}, {'is_past': True, 'title': 'VP of Business and Product Development', 'person': {'first_name': 'Josh', 'last_name': 'Mackey', 'permalink': 'josh-mackey'}}, {'is_past': True, 'title': 'Executive Administrator', 'person': {'first_name': 'Cara', 'last_name': 'Meduri', 'permalink': 'cara-meduri'}}, {'is_past': True, 'title': 'Advisor', 'person': {'first_name': 'Dave', 'last_name': 'Armon', 'permalink': 'dave-armon'}}, {'is_past': True, 'title': 'General Manager', 'person': {'first_name': 'Raj', 'last_name': 'Ajrawat', 'permalink': 'raj-ajrawat'}}, {'is_past': True, 'title': 'Board of Advisors', 'person': {'first_name': 'Ronald', 'last_name': 'Wagner', 'permalink': 'ronald-wagner'}}], 'competitions': [{'competitor': {'name': 'Spock', 'permalink': 'spock'}}, {'competitor': {'name': 'LinkedIn', 'permalink': 'linkedin'}}, {'competitor': {'name': 'Wink', 'permalink': 'wink'}}, {'competitor': {'name': 'Bigsight Media Group', 'permalink': 'bigsight-media-group'}}, {'competitor': {'name': 'Rapleaf', 'permalink': 'rapleaf'}}, {'competitor': {'name': 'Qwerly', 'permalink': 'qwerly'}}, {'competitor': {'name': 'Ark', 'permalink': 'ark'}}], 'providerships': [{'title': 'Colocation Provider', 'is_past': False, 'provider': {'name': 'Cogent', 'permalink': 'cogent'}}, {'title': 'Public Relations', 'is_past': False, 'provider': {'name': '5WPR | 5W Public Relations', 'permalink': '5w-public-relations'}}, {'title': 'Hard Drive Provider', 'is_past': False, 'provider': {'name': 'Texas Memory Systems', 'permalink': 'texas-memory-systems'}}, {'title': 'Web Hosting', 'is_past': False, 'provider': {'name': 'Amazon Web Services', 'permalink': 'amazon'}}, {'title': 'Investment Banking', 'is_past': False, 'provider': {'name': 'Garros Group', 'permalink': 'garros-group'}}], 'total_money_raised': '$1.83M', 'funding_rounds': [{'id': 631, 'round_code': 'angel', 'source_url': 'http://business.maktoob.com/NewsDetails-20070423109438-PeekYou_Emerges_From_Stealth_Mode_With_50_Million_Profiles_in_Beta_Providing_Easy_and_Efficient_People_Search_CapabilitiesRateMyTeachers_com_Founder_Seeks_to_Meet_Growing_Demand_for_Online_People_Sea.', 'source_description': '', 'raised_amount': 1500000, 'raised_currency_code': 'USD', 'funded_year': 2006, 'funded_month': 8, 'funded_day': 1, 'investments': [{'company': {'name': 'Duggal Visual Solutions', 'permalink': 'duggal-visual-solutions'}, 'financial_org': None, 'person': None}]}, {'id': 24725, 'round_code': 'angel', 'source_url': '', 'source_description': '', 'raised_amount': 50000, 'raised_currency_code': 'USD', 'funded_year': 2010, 'funded_month': 7, 'funded_day': 1, 'investments': [{'company': None, 'financial_org': None, 'person': {'first_name': 'Peter', 'last_name': 'Bordes', 'permalink': 'peter-bordes'}}]}, {'id': 24726, 'round_code': 'angel', 'source_url': '', 'source_description': '', 'raised_amount': 100000, 'raised_currency_code': 'USD', 'funded_year': 2011, 'funded_month': 7, 'funded_day': 1, 'investments': [{'company': None, 'financial_org': None, 'person': {'first_name': 'Peter', 'last_name': 'Bordes', 'permalink': 'peter-bordes'}}]}, {'id': 24727, 'round_code': 'angel', 'source_url': '', 'source_description': '', 'raised_amount': 75000, 'raised_currency_code': 'USD', 'funded_year': 2011, 'funded_month': 7, 'funded_day': 1, 'investments': [{'company': None, 'financial_org': None, 'person': {'first_name': 'Joseph', 'last_name': 'Saviano', 'permalink': 'joseph-saviano'}}]}, {'id': 28957, 'round_code': 'seed', 'source_url': '', 'source_description': '', 'raised_amount': 100000, 'raised_currency_code': 'USD', 'funded_year': 2011, 'funded_month': 8, 'funded_day': 1, 'investments': [{'company': {'name': 'TMT Investments', 'permalink': 'tmt-investments'}, 'financial_org': None, 'person': None}]}], 'investments': [], 'acquisition': None, 'acquisitions': [], 'offices': {'description': None, 'address1': None, 'address2': None, 'zip_code': None, 'city': 'New York', 'state_code': 'NY', 'country_code': 'USA', 'latitude': 40.757929, 'longitude': -73.985506}, 'milestones': [{'id': 18106, 'description': 'Launched in Stealth Mode', 'stoned_year': 2006, 'stoned_month': 7, 'stoned_day': 15, 'source_url': 'http://en.wikipedia.org/wiki/PeekYou', 'source_text': None, 'source_description': '', 'stoneable_type': 'Company', 'stoned_value': None, 'stoned_value_type': None, 'stoned_acquirer': None, 'stoneable': {'name': 'PeekYou', 'permalink': 'peekyou'}}], 'ipo': None, 'video_embeds': [{'embed_code': '<object width="420" height="280"><param name="movie" value="http://www.youtube.com/v/7ERcJKJHD6E&hl=en_US&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/7ERcJKJHD6E&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="420" height="280"></embed></object>', 'description': '<p>Interview with PeekYou founder Michael Hussey</p>'}, {'embed_code': '<script src="http://player.ooyala.com/player.js?embedCode=l3a3VnMjr4y4Xa3UEqKZrZnQOZAveJRg&height=230&video_pcode=11amo6qGw2oucN78pR-BYbDpCESk&width=420&deepLinkEmbedCode=l3a3VnMjr4y4Xa3UEqKZrZnQOZAveJRg"></script>', 'description': '<p>Techcrunch Disrupt 2011  Backstage: CEO Mike Hussey</p>'}, {'embed_code': '<iframe width="420" height="315" src="http://www.youtube.com/embed/RftFyPfYQxA" frameborder="0" allowfullscreen></iframe>', 'description': '<p>On MSNBC discussing Newt Gingrich, Twitter followers and PeekYou / PeekAnalytics</p>'}], 'screenshots': [], 'external_links': [{'external_url': 'http://www.webmetricsguru.com/archives/2010/09/peekyou-starbucks-case-study-using-peekdata-reverse-url-indentity-lookups-social-media-monitoring-platforms-will-improve-when-using-this-data/', 'title': 'PeekYou â€“ Starbucks case study using PeekData reverse url indentity lookups  '}, {'external_url': 'http://www.webmetricsguru.com/archives/2010/09/peekyou-starbucks-case-study-using-peekdata-reverse-url-indentity-lookups-social-media-monitoring-platforms-will-improve-when-using-this-data/', 'title': 'Twitter Account Reverse Lookup Case Study from PeekYou  Read more: http://www.webmetricsguru.com/archives/2010/09/twitter-account-reverse-lookup-case-study'}, {'external_url': 'http://www.webmetricsguru.com/archives/2010/09/peekyou-deeppeek-geolocaton-deep-dive-on-starbucks/', 'title': 'PeekYou DeepPeek GeoLocaton Deep Dive on Starbucks Posted by Marshall Sponder on September 24, 2010 | Link It  URL Link \t HTML Link \t BBCode Link \t Trackback \t  X Welcome Googler! If you find this page useful, why not subscribe to the RSS feed for more in'}, {'external_url': 'http://online.wsj.com/article/SB10001424052748703358504575544381288117888.html#ixzz128rgI7SG', 'title': "'Scrapers' Dig Deep for Data on Web "}, {'external_url': 'http://news.yahoo.com/s/prweb/20110420/bs_prweb/prweb5263824_1', 'title': 'PeekYou Teams Up with Reputation.com Providing Customers with Easy and Automatic Privacy Opt-Out'}], 'partners': [], 'location': [{'type': 'Point', 'coordinates': [-73.985506, 40.757929]}], 'geolocation': {'type': 'Point', 'coordinates': [-73.985506, 40.757929]}}

In [310]:
def getLocation(companies):
    for i in range(len(companies['offices'])):
        longitude = companies['offices']['longitude']
        latitude = companies['offices']['latitude']
        loc = {
            'type':'Point',
            'coordinates':[longitude, latitude]
        }
        return loc

In [311]:
getLocation(oficinas_fuera[1])

{'type': 'Point', 'coordinates': [-111.9035, 33.8171]}

In [312]:
for cp in oficinas_fuera:
    value = {"$set": {'geolocation':getLocation(cp)}}
    coll.update_one(cp, value)

In [313]:
print(oficinas_fuera[0])

{'_id': ObjectId('52cdef7c4bab8bd675297f94'), 'name': 'PeekYou', 'permalink': 'peekyou', 'crunchbase_url': 'http://www.crunchbase.com/company/peekyou', 'homepage_url': 'http://www.peekyou.com', 'blog_url': 'http://www.peekyou.biz', 'blog_feed_url': 'http://blog.peekyou.com/feed/', 'twitter_username': 'peekyou', 'category_code': 'search', 'number_of_employees': 20, 'founded_year': 2012, 'founded_month': 11, 'founded_day': 2, 'deadpooled_year': None, 'deadpooled_month': None, 'deadpooled_day': None, 'deadpooled_url': None, 'tag_list': 'social-crm, database, peekyou, peoplesearch, engine, people, search, directory, social, google', 'alias_list': None, 'email_address': 'info@peekyou.com', 'phone_number': '', 'description': '', 'created_at': 'Fri Aug 31 12:46:53 UTC 2007', 'updated_at': 'Wed Jul 10 10:13:16 UTC 2013', 'overview': '<p>PeekYou places the individual at the center of the Internet. For every public weblink, PeekYou tries to answer the question, &#8220;Who made it?&#8221; or, where applicable, &#8220;Whom is it about?&#8221; So far, we&#8217;ve answered those questions for a billion links and counting. Our patented technology analyzes content from over sixty social sites, news sources, homepages and blog platforms and identifies the actual people behind it, combining their scattered digital footprints into a comprehensive record of their online identity.</p>\n\n<p>Google calculates the likelihood of any link being associated to a keyword. PeekYou calculates the likelihood of any link being associated to an individual.</p>\n\n<p>The company was founded in 2006 by Michael Hussey and is headquartered in New York City.</p>', 'image': {'available_sizes': [[[150, 36], 'assets/images/resized/0011/9733/119733v6-max-150x150.png'], [[250, 61], 'assets/images/resized/0011/9733/119733v6-max-250x250.png'], [[413, 101], 'assets/images/resized/0011/9733/119733v6-max-450x450.png']], 'attribution': None}, 'products': [{'name': 'PeekYou.com', 'permalink': 'peekyou'}, {'name': 'PeekAnalytics', 'permalink': 'peekanalytics'}, {'name': 'PeekAPI', 'permalink': 'peekapi'}], 'relationships': [{'is_past': False, 'title': 'Chairman of the Board', 'person': {'first_name': 'Kimberley', 'last_name': 'Partoll', 'permalink': 'kimberley-partoll'}}, {'is_past': False, 'title': 'CEO/Founder', 'person': {'first_name': 'Michael', 'last_name': 'Hussey', 'permalink': 'michael-hussey'}}, {'is_past': False, 'title': 'CTO', 'person': {'first_name': 'Venky', 'last_name': 'Someswaran', 'permalink': 'venky-someswaran'}}, {'is_past': False, 'title': 'CIO', 'person': {'first_name': 'Pavel', 'last_name': 'Baranov', 'permalink': 'pavel-baranov'}}, {'is_past': False, 'title': 'VP of Operations', 'person': {'first_name': 'Chris', 'last_name': 'Klipple', 'permalink': 'chris-klipple'}}, {'is_past': False, 'title': 'Lead Developer', 'person': {'first_name': 'Eray', 'last_name': 'Cetiner', 'permalink': 'eray-cetiner'}}, {'is_past': False, 'title': 'Director', 'person': {'first_name': 'Baldev', 'last_name': 'Duggal', 'permalink': 'baldev-duggal'}}, {'is_past': False, 'title': 'President', 'person': {'first_name': 'Tom', 'last_name': 'Lynch', 'permalink': 'tom-lynch'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Andy', 'last_name': 'Tuck', 'permalink': 'andy-tuck'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Marshall', 'last_name': 'Sponder', 'permalink': 'marshall-sponder'}}, {'is_past': False, 'title': 'Lead Developer', 'person': {'first_name': 'Dasara', 'last_name': 'Kushi', 'permalink': 'dasara-kushi'}}, {'is_past': False, 'title': 'Art Director', 'person': {'first_name': 'Lane', 'last_name': 'Gillespie', 'permalink': 'lane-gillespie'}}, {'is_past': False, 'title': 'Investment Banker', 'person': {'first_name': 'Phil', 'last_name': 'Fresen', 'permalink': 'phil-fresen'}}, {'is_past': False, 'title': 'Developer', 'person': {'first_name': 'Oleg', 'last_name': 'Borkov', 'permalink': 'oleg-borkov'}}, {'is_past': False, 'title': 'Board of Directors', 'person': {'first_name': 'Peter', 'last_name': 'Bordes', 'permalink': 'peter-bordes'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Francine', 'last_name': 'Hardaway', 'permalink': 'francine-hardaway'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Sebastian', 'last_name': 'Haigh', 'permalink': 'sebastian-haigh'}}, {'is_past': False, 'title': 'Advisor', 'person': {'first_name': 'Stephen', 'last_name': 'Shearin', 'permalink': 'stephen-shearin'}}, {'is_past': False, 'title': 'Software Engineer', 'person': {'first_name': 'Amauris', 'last_name': 'De Jesus', 'permalink': 'amauris-de-jesus'}}, {'is_past': False, 'title': 'Software Engineer', 'person': {'first_name': 'Mikhail', 'last_name': 'Dovgilev', 'permalink': 'mikhail-dovgilev'}}, {'is_past': False, 'title': 'Developer', 'person': {'first_name': 'Ronn', 'last_name': 'Tan', 'permalink': 'ronn-tan'}}, {'is_past': True, 'title': 'CFO', 'person': {'first_name': 'Tom', 'last_name': 'Lynch', 'permalink': 'tom-lynch'}}, {'is_past': True, 'title': 'President/COO', 'person': {'first_name': 'Eric', 'last_name': 'Ludwig', 'permalink': 'eric-ludwig-3'}}, {'is_past': True, 'title': 'VP of Business and Product Development', 'person': {'first_name': 'Josh', 'last_name': 'Mackey', 'permalink': 'josh-mackey'}}, {'is_past': True, 'title': 'Executive Administrator', 'person': {'first_name': 'Cara', 'last_name': 'Meduri', 'permalink': 'cara-meduri'}}, {'is_past': True, 'title': 'Advisor', 'person': {'first_name': 'Dave', 'last_name': 'Armon', 'permalink': 'dave-armon'}}, {'is_past': True, 'title': 'General Manager', 'person': {'first_name': 'Raj', 'last_name': 'Ajrawat', 'permalink': 'raj-ajrawat'}}, {'is_past': True, 'title': 'Board of Advisors', 'person': {'first_name': 'Ronald', 'last_name': 'Wagner', 'permalink': 'ronald-wagner'}}], 'competitions': [{'competitor': {'name': 'Spock', 'permalink': 'spock'}}, {'competitor': {'name': 'LinkedIn', 'permalink': 'linkedin'}}, {'competitor': {'name': 'Wink', 'permalink': 'wink'}}, {'competitor': {'name': 'Bigsight Media Group', 'permalink': 'bigsight-media-group'}}, {'competitor': {'name': 'Rapleaf', 'permalink': 'rapleaf'}}, {'competitor': {'name': 'Qwerly', 'permalink': 'qwerly'}}, {'competitor': {'name': 'Ark', 'permalink': 'ark'}}], 'providerships': [{'title': 'Colocation Provider', 'is_past': False, 'provider': {'name': 'Cogent', 'permalink': 'cogent'}}, {'title': 'Public Relations', 'is_past': False, 'provider': {'name': '5WPR | 5W Public Relations', 'permalink': '5w-public-relations'}}, {'title': 'Hard Drive Provider', 'is_past': False, 'provider': {'name': 'Texas Memory Systems', 'permalink': 'texas-memory-systems'}}, {'title': 'Web Hosting', 'is_past': False, 'provider': {'name': 'Amazon Web Services', 'permalink': 'amazon'}}, {'title': 'Investment Banking', 'is_past': False, 'provider': {'name': 'Garros Group', 'permalink': 'garros-group'}}], 'total_money_raised': '$1.83M', 'funding_rounds': [{'id': 631, 'round_code': 'angel', 'source_url': 'http://business.maktoob.com/NewsDetails-20070423109438-PeekYou_Emerges_From_Stealth_Mode_With_50_Million_Profiles_in_Beta_Providing_Easy_and_Efficient_People_Search_CapabilitiesRateMyTeachers_com_Founder_Seeks_to_Meet_Growing_Demand_for_Online_People_Sea.', 'source_description': '', 'raised_amount': 1500000, 'raised_currency_code': 'USD', 'funded_year': 2006, 'funded_month': 8, 'funded_day': 1, 'investments': [{'company': {'name': 'Duggal Visual Solutions', 'permalink': 'duggal-visual-solutions'}, 'financial_org': None, 'person': None}]}, {'id': 24725, 'round_code': 'angel', 'source_url': '', 'source_description': '', 'raised_amount': 50000, 'raised_currency_code': 'USD', 'funded_year': 2010, 'funded_month': 7, 'funded_day': 1, 'investments': [{'company': None, 'financial_org': None, 'person': {'first_name': 'Peter', 'last_name': 'Bordes', 'permalink': 'peter-bordes'}}]}, {'id': 24726, 'round_code': 'angel', 'source_url': '', 'source_description': '', 'raised_amount': 100000, 'raised_currency_code': 'USD', 'funded_year': 2011, 'funded_month': 7, 'funded_day': 1, 'investments': [{'company': None, 'financial_org': None, 'person': {'first_name': 'Peter', 'last_name': 'Bordes', 'permalink': 'peter-bordes'}}]}, {'id': 24727, 'round_code': 'angel', 'source_url': '', 'source_description': '', 'raised_amount': 75000, 'raised_currency_code': 'USD', 'funded_year': 2011, 'funded_month': 7, 'funded_day': 1, 'investments': [{'company': None, 'financial_org': None, 'person': {'first_name': 'Joseph', 'last_name': 'Saviano', 'permalink': 'joseph-saviano'}}]}, {'id': 28957, 'round_code': 'seed', 'source_url': '', 'source_description': '', 'raised_amount': 100000, 'raised_currency_code': 'USD', 'funded_year': 2011, 'funded_month': 8, 'funded_day': 1, 'investments': [{'company': {'name': 'TMT Investments', 'permalink': 'tmt-investments'}, 'financial_org': None, 'person': None}]}], 'investments': [], 'acquisition': None, 'acquisitions': [], 'offices': {'description': None, 'address1': None, 'address2': None, 'zip_code': None, 'city': 'New York', 'state_code': 'NY', 'country_code': 'USA', 'latitude': 40.757929, 'longitude': -73.985506}, 'milestones': [{'id': 18106, 'description': 'Launched in Stealth Mode', 'stoned_year': 2006, 'stoned_month': 7, 'stoned_day': 15, 'source_url': 'http://en.wikipedia.org/wiki/PeekYou', 'source_text': None, 'source_description': '', 'stoneable_type': 'Company', 'stoned_value': None, 'stoned_value_type': None, 'stoned_acquirer': None, 'stoneable': {'name': 'PeekYou', 'permalink': 'peekyou'}}], 'ipo': None, 'video_embeds': [{'embed_code': '<object width="420" height="280"><param name="movie" value="http://www.youtube.com/v/7ERcJKJHD6E&hl=en_US&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/7ERcJKJHD6E&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="420" height="280"></embed></object>', 'description': '<p>Interview with PeekYou founder Michael Hussey</p>'}, {'embed_code': '<script src="http://player.ooyala.com/player.js?embedCode=l3a3VnMjr4y4Xa3UEqKZrZnQOZAveJRg&height=230&video_pcode=11amo6qGw2oucN78pR-BYbDpCESk&width=420&deepLinkEmbedCode=l3a3VnMjr4y4Xa3UEqKZrZnQOZAveJRg"></script>', 'description': '<p>Techcrunch Disrupt 2011  Backstage: CEO Mike Hussey</p>'}, {'embed_code': '<iframe width="420" height="315" src="http://www.youtube.com/embed/RftFyPfYQxA" frameborder="0" allowfullscreen></iframe>', 'description': '<p>On MSNBC discussing Newt Gingrich, Twitter followers and PeekYou / PeekAnalytics</p>'}], 'screenshots': [], 'external_links': [{'external_url': 'http://www.webmetricsguru.com/archives/2010/09/peekyou-starbucks-case-study-using-peekdata-reverse-url-indentity-lookups-social-media-monitoring-platforms-will-improve-when-using-this-data/', 'title': 'PeekYou â€“ Starbucks case study using PeekData reverse url indentity lookups  '}, {'external_url': 'http://www.webmetricsguru.com/archives/2010/09/peekyou-starbucks-case-study-using-peekdata-reverse-url-indentity-lookups-social-media-monitoring-platforms-will-improve-when-using-this-data/', 'title': 'Twitter Account Reverse Lookup Case Study from PeekYou  Read more: http://www.webmetricsguru.com/archives/2010/09/twitter-account-reverse-lookup-case-study'}, {'external_url': 'http://www.webmetricsguru.com/archives/2010/09/peekyou-deeppeek-geolocaton-deep-dive-on-starbucks/', 'title': 'PeekYou DeepPeek GeoLocaton Deep Dive on Starbucks Posted by Marshall Sponder on September 24, 2010 | Link It  URL Link \t HTML Link \t BBCode Link \t Trackback \t  X Welcome Googler! If you find this page useful, why not subscribe to the RSS feed for more in'}, {'external_url': 'http://online.wsj.com/article/SB10001424052748703358504575544381288117888.html#ixzz128rgI7SG', 'title': "'Scrapers' Dig Deep for Data on Web "}, {'external_url': 'http://news.yahoo.com/s/prweb/20110420/bs_prweb/prweb5263824_1', 'title': 'PeekYou Teams Up with Reputation.com Providing Customers with Easy and Automatic Privacy Opt-Out'}], 'partners': [], 'location': [{'type': 'Point', 'coordinates': [-73.985506, 40.757929]}], 'geolocation': {'type': 'Point', 'coordinates': [-73.985506, 40.757929]}}

In [314]:
companies_df = pd.DataFrame(oficinas_fuera)

companies_df

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners,location,geolocation
0,52cdef7c4bab8bd675297f94,PeekYou,peekyou,http://www.crunchbase.com/company/peekyou,http://www.peekyou.com,http://www.peekyou.biz,http://blog.peekyou.com/feed/,peekyou,search,20.0,...,[],"{'description': None, 'address1': None, 'addre...","[{'id': 18106, 'description': 'Launched in Ste...",None,"[{'embed_code': '<object width=""420"" height=""2...",[],[{'external_url': 'http://www.webmetricsguru.c...,[],"[{'type': 'Point', 'coordinates': [-73.985506,...","{'type': 'Point', 'coordinates': [-73.985506, ..."
1,52cdef7c4bab8bd675297f9e,GENWI,genwi,http://www.crunchbase.com/company/genwi,http://www.genwi.com,http://blog.genwi.com,,genwi,mobile,25.0,...,[],"{'description': '', 'address1': '4966 El Camin...","[{'id': 14542, 'description': 'Rahul Patel, fo...",None,[],"[{'available_sizes': [[[150, 96], 'assets/imag...","[{'external_url': 'http://iSites.us', 'title':...",[],"[{'type': 'Point', 'coordinates': [-111.9035, ...","{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,52cdef7c4bab8bd675297fec,Fixya,fixya,http://www.crunchbase.com/company/fixya,http://www.fixya.com,http://blog.muktar.com,http://blog.muktar.com/feed/,MUaliyu,web,30.0,...,[],"{'description': '', 'address1': 'One Franklin ...",[],None,"[{'embed_code': '<div style=""width:320px;""><di...",[],[{'external_url': 'http://www.vccafe.com/2009/...,[],"[{'type': 'Point', 'coordinates': [-122.323895...","{'type': 'Point', 'coordinates': [-122.323895,..."
3,52cdef7c4bab8bd6752981d8,Widgetbox,widgetbox,http://www.crunchbase.com/company/widgetbox,http://widgetbox.com,,http://blog.widgetbox.com/feed/,widgetbox,other,30.0,...,[],"{'description': None, 'address1': None, 'addre...","[{'id': 1669, 'description': 'Widgetizing The ...",None,[],"[{'available_sizes': [[[100, 75], 'assets/imag...",[],[],"[{'type': 'Point', 'coordinates': [-122.398599...","{'type': 'Point', 'coordinates': [-122.398599,..."
4,52cdef7c4bab8bd6752981dc,RazorGator,razorgator,http://www.crunchbase.com/company/razorgator,http://razorgator.com,,,Razorgator,ecommerce,NaN,...,[],"{'description': None, 'address1': '11150 Santa...",[],None,[],[],[],[],"[{'type': 'Point', 'coordinates': [-118.445243...","{'type': 'Point', 'coordinates': [-118.445243,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,52cdef7f4bab8bd67529c2d0,Delphi,delphi,http://www.crunchbase.com/company/delphi,http://www.delphi.com,,,DelphiAuto,cleantech,NaN,...,[],"{'description': '', 'address1': '5725 Delphi D...",[],None,[],"[{'available_sizes': [[[150, 75], 'assets/imag...",[],[],"[{'type': 'Point', 'coordinates': [-83.16134, ...","{'type': 'Point', 'coordinates': [-83.16134, 4..."
102,52cdef7f4bab8bd67529c343,ChallengePost,challengepost,http://www.crunchbase.com/company/challengepost,http://www.challengepost.com,http://blog.challengepost.com,,challengepost,web,17.0,...,[],"{'description': '', 'address1': '425 West 13th...",[],None,[],"[{'available_sizes': [[[150, 136], 'assets/ima...",[],[],"[{'type': 'Point', 'coordinates': [-74.00717, ...","{'type': 'Point', 'coordinates': [-74.00717, 4..."
103,52cdef7f4bab8bd67529c448,Teambox,teambox,http://www.crunchbase.com/company/teambox,http://www.teambox.com,http://teambox.com/blog,,teambox_app,web,35.0,...,"[{'price_amount': None, 'price_currency_code':...","{'description': 'Barcelona Office', 'address1'...","[{'id': 23211, 'description': 'Teambox hires D...",None,"[{'embed_code': '<iframe src="""">Teambox online...","[{'available_sizes': [[[150, 83], 'assets/imag...",[],"[{'partner_name': 'AngelList', 'homepage_url':...",NaN,"{'type': 'Point', 'coordinates': [2.1920231, 4..."
104,52cdef7f4bab8bd67529c6b6,Tiny Speck,tiny-speck,http://www.crunchbase.com/company/tiny-speck,http://tinyspeck.com,,,slackhq,games_video,45.0,...,[],"{'description': '', 'address1': '163 Hastings ...",[],None,[],"[{'available_sizes': [[[150, 73], 'assets/imag...",[],[],"[{'type': 'Point', 'coordinates': [-123.109217...","{'type': 'Point', 'coordinates': [-123.109217,..."
105,52cdef7f4bab8bd67529c6e4,Getyoo,getyoo,http://www.crunchbase.com/company/getyoo,http://www.getyoo.com,http://getyoo.tumblr.com/,http://getyoo.tumblr.com/rss,getyoo,mobile,10.0,...,[],"{'description': 'HQ', 'address1': 'Rue des Tan...",[],None,"[{'embed_code': '<object width=""448"" height=""2...","[{'available_sizes': [[[150, 93], 'assets/imag...",[{'external_url': 'http://www.youtube.com/watc...,[],"[{'type': 'Point', 'coordinates': [4.3464721, ...","{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [315]:
print(len(companies_df))

106

In [316]:
companies_df1 = companies_df[["name","category_code","founded_year","total_money_raised","geolocation"]]

companies_df1

,name,category_code,founded_year,total_money_raised,geolocation
0,PeekYou,search,2012,$1.83M,"{'type': 'Point', 'coordinates': [-73.985506, ..."
1,GENWI,mobile,2010,$7.1M,"{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,Fixya,web,2013,$8M,"{'type': 'Point', 'coordinates': [-122.323895,..."
3,Widgetbox,other,2012,$14.5M,"{'type': 'Point', 'coordinates': [-122.398599,..."
4,RazorGator,ecommerce,2011,$58.8M,"{'type': 'Point', 'coordinates': [-118.445243,..."
...,...,...,...,...,...
101,Delphi,cleantech,2009,$8M,"{'type': 'Point', 'coordinates': [-83.16134, 4..."
102,ChallengePost,web,2009,$4.6M,"{'type': 'Point', 'coordinates': [-74.00717, 4..."
103,Teambox,web,2009,$6.75M,"{'type': 'Point', 'coordinates': [2.1920231, 4..."
104,Tiny Speck,games_video,2009,$17.2M,"{'type': 'Point', 'coordinates': [-123.109217,..."
105,Getyoo,mobile,2009,€1.13M,"{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [317]:
companies_df1['category_code'].value_counts()

web                15
games_video        14
software           14
advertising        14
enterprise          9
mobile              8
travel              5
ecommerce           5
biotech             4
social              2
search              2
cleantech           2
other               2
education           2
hardware            2
medical             1
fashion             1
network_hosting     1
security            1
analytics           1
messaging           1
Name: category_code, dtype: int64

In [318]:
category_list = {'web': 'tech', 'games_video': 'tech', 'software':'tech', 'advertising':'tech', 
                 'mobile':'tech', 'ecommerce':'tech', 'biotech':'tech', 'search':'tech',
                 'cleantech':'tech','hardware':'tech', 'netword_hosting':'tech', 'security':'tech', 
                 'analytics':'tech'}

In [319]:
companies_df2 = companies_df1.replace(to_replace = category_list, inplace=False) 

companies_df2.head(40)

,name,category_code,founded_year,total_money_raised,geolocation
0,PeekYou,tech,2012,$1.83M,"{'type': 'Point', 'coordinates': [-73.985506, ..."
1,GENWI,tech,2010,$7.1M,"{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,Fixya,tech,2013,$8M,"{'type': 'Point', 'coordinates': [-122.323895,..."
3,Widgetbox,other,2012,$14.5M,"{'type': 'Point', 'coordinates': [-122.398599,..."
4,RazorGator,tech,2011,$58.8M,"{'type': 'Point', 'coordinates': [-118.445243,..."
5,Social Gaming Network,tech,2011,$17.1M,"{'type': 'Point', 'coordinates': [-122.161523,..."
6,Social Gaming Network,tech,2011,$17.1M,"{'type': 'Point', 'coordinates': [-122.161523,..."
7,Skydeck,tech,2012,$4M,"{'type': 'Point', 'coordinates': [-122.3254705..."
8,Handipoints,tech,2009,$800k,"{'type': 'Point', 'coordinates': [-122.214897,..."
9,Magento,tech,2010,$22.5M,"{'type': 'Point', 'coordinates': [-118.243425,..."
10,Pixsta,tech,2010,£3M,"{'type': 'Point', 'coordinates': [-0.208979, 5..."
11,FirstString,tech,2011,$200k,"{'type': 'Point', 'coordinates': [-118.243425,..."
12,BrandYourself,tech,2009,$1.5M,"{'type': 'Point', 'coordinates': [-71.24762, 4..."
13,Titan Gaming,tech,2010,$1M,"{'type': 'Point', 'coordinates': [-113.515769,..."
14,Prezi,tech,2009,$14.3M,"{'type': 'Point', 'coordinates': [19.059078, 4..."
15,CompareAway,tech,2009,£500k,"{'type': 'Point', 'coordinates': [-1.574948, 5..."
16,GetYourGuide,travel,2009,$16M,"{'type': 'Point', 'coordinates': [8.5082891, 4..."
17,Integrate,tech,2010,$34.8M,"{'type': 'Point', 'coordinates': [-74.0353787,..."
18,vufind,tech,2010,$930k,"{'type': 'Point', 'coordinates': [-122.145153,..."
19,travelmob,travel,2011,$1M,"{'type': 'Point', 'coordinates': [-157.78907, ..."
20,UsingMiles,travel,2010,$3.27M,"{'type': 'Point', 'coordinates': [-104.9998449..."
21,Burt,tech,2009,$3.5M,"{'type': 'Point', 'coordinates': [18.036587, 5..."
22,Inuvo,tech,2009,$4.2M,"{'type': 'Point', 'coordinates': [-82.702449, ..."
23,Kidos,tech,2011,$200k,"{'type': 'Point', 'coordinates': [-73.956599, ..."
24,Kidos,tech,2011,$200k,"{'type': 'Point', 'coordinates': [-73.956599, ..."
25,Integrate,tech,2010,$34.8M,"{'type': 'Point', 'coordinates': [-74.0353787,..."
26,vufind,tech,2010,$930k,"{'type': 'Point', 'coordinates': [-122.145153,..."
27,travelmob,travel,2011,$1M,"{'type': 'Point', 'coordinates': [-157.78907, ..."
28,UsingMiles,travel,2010,$3.27M,"{'type': 'Point', 'coordinates': [-104.9998449..."
29,Burt,tech,2009,$3.5M,"{'type': 'Point', 'coordinates': [18.036587, 5..."
30,Inuvo,tech,2009,$4.2M,"{'type': 'Point', 'coordinates': [-82.702449, ..."
31,Kidos,tech,2011,$200k,"{'type': 'Point', 'coordinates': [-73.956599, ..."
32,Kidos,tech,2011,$200k,"{'type': 'Point', 'coordinates': [-73.956599, ..."
33,Formspring,tech,2009,$14.3M,"{'type': 'Point', 'coordinates': [-86.0547016,..."
34,isocket,tech,2009,$10.1M,"{'type': 'Point', 'coordinates': [-122.321836,..."
35,Yipit,tech,2010,$7.55M,"{'type': 'Point', 'coordinates': [-73.987764, ..."
36,StudyBlue,education,2009,$18.5M,"{'type': 'Point', 'coordinates': [-89.39256, 4..."
37,HyperWeek,social,2009,$1.31M,"{'type': 'Point', 'coordinates': [6.1503245, 4..."
38,Queralt,enterprise,2011,$650k,"{'type': 'Point', 'coordinates': [-72.8190106,..."
39,FeedHenry,enterprise,2010,$9M,"{'type': 'Point', 'coordinates': [-71.2089211,..."

In [320]:
companies_df3 = companies_df2[['tech' in x for x in companies_df2['category_code']]]
companies_df3

,name,category_code,founded_year,total_money_raised,geolocation
0,PeekYou,tech,2012,$1.83M,"{'type': 'Point', 'coordinates': [-73.985506, ..."
1,GENWI,tech,2010,$7.1M,"{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,Fixya,tech,2013,$8M,"{'type': 'Point', 'coordinates': [-122.323895,..."
4,RazorGator,tech,2011,$58.8M,"{'type': 'Point', 'coordinates': [-118.445243,..."
5,Social Gaming Network,tech,2011,$17.1M,"{'type': 'Point', 'coordinates': [-122.161523,..."
...,...,...,...,...,...
101,Delphi,tech,2009,$8M,"{'type': 'Point', 'coordinates': [-83.16134, 4..."
102,ChallengePost,tech,2009,$4.6M,"{'type': 'Point', 'coordinates': [-74.00717, 4..."
103,Teambox,tech,2009,$6.75M,"{'type': 'Point', 'coordinates': [2.1920231, 4..."
104,Tiny Speck,tech,2009,$17.2M,"{'type': 'Point', 'coordinates': [-123.109217,..."
105,Getyoo,tech,2009,€1.13M,"{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [321]:
companies_df3.total_money_raised = companies_df3.total_money_raised.str.replace(r'(\d+)([A-Za-z])', r'\1 \2')

companies_df3

,name,category_code,founded_year,total_money_raised,geolocation
0,PeekYou,tech,2012,$1.83 M,"{'type': 'Point', 'coordinates': [-73.985506, ..."
1,GENWI,tech,2010,$7.1 M,"{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,Fixya,tech,2013,$8 M,"{'type': 'Point', 'coordinates': [-122.323895,..."
4,RazorGator,tech,2011,$58.8 M,"{'type': 'Point', 'coordinates': [-118.445243,..."
5,Social Gaming Network,tech,2011,$17.1 M,"{'type': 'Point', 'coordinates': [-122.161523,..."
...,...,...,...,...,...
101,Delphi,tech,2009,$8 M,"{'type': 'Point', 'coordinates': [-83.16134, 4..."
102,ChallengePost,tech,2009,$4.6 M,"{'type': 'Point', 'coordinates': [-74.00717, 4..."
103,Teambox,tech,2009,$6.75 M,"{'type': 'Point', 'coordinates': [2.1920231, 4..."
104,Tiny Speck,tech,2009,$17.2 M,"{'type': 'Point', 'coordinates': [-123.109217,..."
105,Getyoo,tech,2009,€1.13 M,"{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [322]:
companies_df3 = companies_df3[['M' in x for x in companies_df3['total_money_raised']]]
companies_df3

,name,category_code,founded_year,total_money_raised,geolocation
0,PeekYou,tech,2012,$1.83 M,"{'type': 'Point', 'coordinates': [-73.985506, ..."
1,GENWI,tech,2010,$7.1 M,"{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,Fixya,tech,2013,$8 M,"{'type': 'Point', 'coordinates': [-122.323895,..."
4,RazorGator,tech,2011,$58.8 M,"{'type': 'Point', 'coordinates': [-118.445243,..."
5,Social Gaming Network,tech,2011,$17.1 M,"{'type': 'Point', 'coordinates': [-122.161523,..."
...,...,...,...,...,...
101,Delphi,tech,2009,$8 M,"{'type': 'Point', 'coordinates': [-83.16134, 4..."
102,ChallengePost,tech,2009,$4.6 M,"{'type': 'Point', 'coordinates': [-74.00717, 4..."
103,Teambox,tech,2009,$6.75 M,"{'type': 'Point', 'coordinates': [2.1920231, 4..."
104,Tiny Speck,tech,2009,$17.2 M,"{'type': 'Point', 'coordinates': [-123.109217,..."
105,Getyoo,tech,2009,€1.13 M,"{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [323]:
print(companies_df3.reset_index(drop=True))

                     name category_code  founded_year total_money_raised  \
0                 PeekYou          tech          2012            $1.83 M
1                   GENWI          tech          2010             $7.1 M
2                   Fixya          tech          2013               $8 M
3              RazorGator          tech          2011            $58.8 M
4   Social Gaming Network          tech          2011            $17.1 M
..                    ...           ...           ...                ...
56                 Delphi          tech          2009               $8 M
57          ChallengePost          tech          2009             $4.6 M
58                Teambox          tech          2009            $6.75 M
59             Tiny Speck          tech          2009            $17.2 M
60                 Getyoo          tech          2009            €1.13 M

                                          geolocation
0   {'type': 'Point', 'coordinates': [-73.985506, ...
1   {'type': 'Point', 'coordinates': [-111.9035, 3...
2   {'type': 'Point', 'coordinates': [-122.323895,...
3   {'type': 'Point', 'coordinates': [-118.445243,...
4   {'type': 'Point', 'coordinates': [-122.161523,...
..                                                ...
56  {'type': 'Point', 'coordinates': [-83.16134, 4...
57  {'type': 'Point', 'coordinates': [-74.00717, 4...
58  {'type': 'Point', 'coordinates': [2.1920231, 4...
59  {'type': 'Point', 'coordinates': [-123.109217,...
60  {'type': 'Point', 'coordinates': [4.3464721, 5...

[61 rows x 5 columns]

In [324]:

companies_df3.head(20)

,name,category_code,founded_year,total_money_raised,geolocation
0,PeekYou,tech,2012,$1.83 M,"{'type': 'Point', 'coordinates': [-73.985506, ..."
1,GENWI,tech,2010,$7.1 M,"{'type': 'Point', 'coordinates': [-111.9035, 3..."
2,Fixya,tech,2013,$8 M,"{'type': 'Point', 'coordinates': [-122.323895,..."
4,RazorGator,tech,2011,$58.8 M,"{'type': 'Point', 'coordinates': [-118.445243,..."
5,Social Gaming Network,tech,2011,$17.1 M,"{'type': 'Point', 'coordinates': [-122.161523,..."
...,...,...,...,...,...
101,Delphi,tech,2009,$8 M,"{'type': 'Point', 'coordinates': [-83.16134, 4..."
102,ChallengePost,tech,2009,$4.6 M,"{'type': 'Point', 'coordinates': [-74.00717, 4..."
103,Teambox,tech,2009,$6.75 M,"{'type': 'Point', 'coordinates': [2.1920231, 4..."
104,Tiny Speck,tech,2009,$17.2 M,"{'type': 'Point', 'coordinates': [-123.109217,..."
105,Getyoo,tech,2009,€1.13 M,"{'type': 'Point', 'coordinates': [4.3464721, 5..."

In [325]:
companies_df3.to_json('./mycompanies_clean.json', orient='records')